name: Max_AutoNewsbot
on:
  schedule:
    - cron: "30 3 * * *"      # 9:00 AM IST Full Digest
    - cron: "0 */2 * * *"     # Every 2 hours Mini Updates
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Auto News Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot.py
